name: E2E

on:
  push:
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Install Playwright (browsers)
        run: npx playwright install --with-deps

      - name: Build
        run: npm run build

      - name: Start preview
        run: npm run preview &
      
      - name: Wait for server
        run: npx wait-on http://localhost:3000

      - name: Run Playwright
        run: E2E_BASE_URL=http://localhost:3000 npx playwright test

      - name: Upload report on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
